FROM nginx
RUN rm /usr/share/nginx/html/*
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./server.cert /etc/nginx/ssl/server.cert
COPY ./server.key /etc/nginx/ssl/server.key
CMD ["nginx", "-g", "daemon off;"]